"""Add co2 column to SensorData

Revision ID: 19f57397fb08
Revises: 3fe5aaff1227
Create Date: 2025-03-22 22:24:59.364014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f57397fb08'
down_revision = '3fe5aaff1227'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('co2', sa.Float(), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_column('co2')

    # ### end Alembic commands ###
